version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheque_ocr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/cheque_ocr
      - UPLOAD_DIR=/data/uploads
      - AUDIT_ROOT=/data/audit
      - BATCH_MAP_DIR=/data/batch_map
      - BATCH_TZ=Africa/Cairo
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - data:/data
    depends_on:
      - db
volumes:
  pgdata:
  data:
